[tool]
[tool.poetry]
name = "Userbot_Deployer"
version = "1.0"
description = "Automatic Deploy UserBot to Heroku"
authors = ["SakirBey"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
